from typing import List, Optional

from app.crud.base import CRUDBase
from app.models.generated_email import GeneratedEmail
from app.schemas.generated_email import GeneratedEmailCreate, GeneratedEmailUpdate


class CRUDGeneratedEmail(CRUDBase[GeneratedEmail, GeneratedEmailCreate, GeneratedEmailUpdate]):
    """CRUD operations for GeneratedEmail model.
    
    Inherits from CRUDBase and adds email-specific operations.
    """
    
    def create_with_template(
        self, db, *, obj_in: GeneratedEmailCreate, owner_id: int
    ) -> GeneratedEmail:
        """Create a new generated email with an owner and template."""
        obj_in_data = obj_in.dict()
        db_obj = self.model(**obj_in_data, owner_id=owner_id)
        db.add(db_obj)
        db.commit()
        db.refresh(db_obj)
        return db_obj
    
    def get_by_owner(
        self, db, *, owner_id: int, skip: int = 0, limit: int = 100
    ) -> List[GeneratedEmail]:
        """Get all emails generated by a specific user."""
        return (
            db.query(self.model)
            .filter(GeneratedEmail.owner_id == owner_id)
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def get_by_template(
        self, db, *, template_id: int, skip: int = 0, limit: int = 100
    ) -> List[GeneratedEmail]:
        """Get all emails generated from a specific template."""
        return (
            db.query(self.model)
            .filter(GeneratedEmail.template_id == template_id)
            .offset(skip)
            .limit(limit)
            .all()
        )


crud_generated_email = CRUDGeneratedEmail(GeneratedEmail) 